[package]
name = "regex-strings-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
regex = "1.13.1"

[dependencies.regex-strings]
path = ".."

[[bin]]
name = "enumeration_matches_regex"
path = "fuzz_targets/enumeration_matches_regex.rs"
test = false
doc = false
bench = false
