[package]
edition = "2024"
name = "regex-strings-fuzz"
publish = false
version = "0.0.0"

[package.metadata]
cargo-fuzz = true

[dependencies]
arbitrary = "1"
libfuzzer-sys = "0.4"
regex = "1.13.1"

[dependencies.regex-strings]
path = ".."

[[bin]]
bench = false
doc = false
name = "enumeration_matches_regex"
path = "fuzz_targets/enumeration_matches_regex.rs"
test = false
