[package]
name = "regex-strings-demo"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
js-sys = "0.3"
regex = "1.13.1"
regex-strings = { path = ".." }
wasm-bindgen = "0.2"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
